import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { getLogger } from "log4js";
import { resolve } from "path";
import { Service } from "typedi";
import { parseGoogleSheetUrl } from "../../integrations/google-drive/utils/google-drive-url.util";
import { WorkingDirectory } from "../../utils/working-directory";
import { ConfigService, OnboardConfig } from "../config-service";

const logger = getLogger("OnboardingConfigService");

const ONBOARDING_CONFIG_TEMPLATE = {
    _comment: "This is a configuration template for project onboarding. Replace placeholders with actual values.",
    confluence: {
        baseUrl: "https://your-domain.atlassian.net",
    },
    jira: {
        baseUrl: "https://your-domain.atlassian.net",
    },
    projects: {
        ExampleProject: {
            confluence: {
                _comment:
                    "'pages' accepts Confluence page IDs (as strings). 'space' syncs every page in that space key.",
                pages: ["123456789"],
                space: "PROJ",
            },
            jira: {
                _comment: "'tickets' accepts Jira issue keys. Use 'jql' instead to sync all issues matching a query.",
                tickets: ["PROJ-123"],
            },
            googleDocs: {
                _comment: "'docs' accepts Google Docs/Sheets/.docx file IDs from the file's Google Drive URL.",
                docs: ["your-google-doc-id-here"],
            },
            googleSheets: {
                _comment: "A single Google Sheet to sync as structured data. 'range' is optional (A1 notation).",
                spreadsheetId: "your-google-sheet-id-here",
                range: "Sheet1!A1:E100",
            },
            onboardingSheets: [
                {
                    _comment:
                        "A Google Sheet whose cells contain Confluence/Jira/Drive links to resolve and sync automatically.",
                    spreadsheetId: "your-onboarding-links-sheet-id-here",
                },
            ],
        },
    },
};

const GOOGLE_SHEET_ID_PATTERN = /^[a-zA-Z0-9-_]{44}$/;

/**
 * Owns onboarding config file resolution/I/O (.sateng/onboarding.json) and the
 * Google-Sheet-argument parsing, so OnboardCommand only has to parse flags and delegate.
 */
@Service()
export class OnboardingConfigService {
    constructor(
        private readonly configService: ConfigService,
        private readonly dir: WorkingDirectory,
    ) {}

    private get configDir(): string {
        return this.configService.getProjectConfigDir();
    }

    public get configPath(): string {
        return resolve(this.configDir, "onboarding.json");
    }

    public localConfigExists(): boolean {
        return existsSync(this.configPath);
    }

    /** Resolves a relative config path argument against the user's cwd (not the CLI install directory). */
    public resolveConfigArgPath(arg: string): string {
        return resolve(this.dir.cwd, arg);
    }

    public async loadLocalConfig(): Promise<OnboardConfig> {
        return this.configService.loadOnboardingConfig(this.configPath);
    }

    /** Extracts a Google Sheet spreadsheet ID from a raw ID or a docs.google.com/spreadsheets URL, or null. */
    public parseSheetArg(arg: string): string | null {
        if (arg.includes("docs.google.com/spreadsheets")) {
            return parseGoogleSheetUrl(arg);
        }
        return GOOGLE_SHEET_ID_PATTERN.test(arg) ? arg : null;
    }

    private readSourceSheetId(path: string): string | undefined {
        try {
            const raw = JSON.parse(readFileSync(path, "utf-8"));
            return typeof raw?._sourceGoogleSheetId === "string" ? raw._sourceGoogleSheetId : undefined;
        } catch {
            return undefined;
        }
    }

    /**
     * True only when a local .sateng/onboarding.json exists and was hand-written — i.e. it has no
     * `_sourceGoogleSheetId` marker, so it wasn't itself generated by a previous sheet sync. Used
     * to decide whether a remembered sheet is allowed to drive this run: a sheet-derived local file
     * is just a cache of the sheet and should always be refreshed from it, but a hand-written file
     * (e.g. in an unrelated repo) must never be silently overridden by a sheet remembered from a
     * different project.
     */
    public isLocalConfigHandWritten(): boolean {
        return this.localConfigExists() && this.readSourceSheetId(this.configPath) === undefined;
    }

    /**
     * Mirrors a structured project config resolved from a Google Sheet to .sateng/onboarding.json,
     * for local inspection. Refuses to overwrite a local file that wasn't itself generated from a
     * sheet (no `_sourceGoogleSheetId` marker) unless `force` is set, so a hand-written project
     * config is never silently clobbered.
     */
    public saveResolvedConfig(config: OnboardConfig, sourceSheetId: string, force = false): void {
        const targetPath = this.configPath;

        if (existsSync(targetPath) && !force) {
            const existingSourceId = this.readSourceSheetId(targetPath);
            if (existingSourceId === undefined) {
                logger.warn(
                    `.sateng/onboarding.json already exists and was not generated from a Google Sheet — leaving it untouched. Re-run with --force to overwrite it.`,
                );
                return;
            }
        }

        const withSource = {
            _comment:
                "Auto-generated from a structured onboarding Google Sheet, for local inspection only. " +
                "Running 'sat-cli onboard' (with no argument, from any directory) re-fetches this sheet " +
                "(remembered in your personal config — see sat-cli init) and overwrites this file each " +
                "time — edit the sheet, not this file.",
            _sourceGoogleSheetId: sourceSheetId,
            ...config,
        };

        mkdirSync(this.configDir, { recursive: true });
        writeFileSync(targetPath, `${JSON.stringify(withSource, null, 4)}\n`, "utf-8");
        logger.info(`Saved resolved onboarding config from Google Sheet to: ${targetPath}`);
    }

    /**
     * Writes a sample .sateng/onboarding.json to the repo root so users can see how to structure
     * Confluence, Jira, and Google Drive (Docs/Sheets) entries. Never overwrites an existing
     * onboarding.json — writes alongside it as onboarding.sample.json instead.
     */
    public writeSampleConfig(): void {
        const targetPath = this.configPath;
        const outputPath = existsSync(targetPath) ? resolve(this.configDir, "onboarding.sample.json") : targetPath;

        mkdirSync(this.configDir, { recursive: true });
        writeFileSync(outputPath, `${JSON.stringify(ONBOARDING_CONFIG_TEMPLATE, null, 4)}\n`, "utf-8");

        if (outputPath !== targetPath) {
            logger.info(`.sateng/onboarding.json already exists — wrote sample config to: ${outputPath}`);
        } else {
            logger.info(`Sample onboarding config written to: ${outputPath}`);
        }
        logger.info("Edit it with your Confluence/Jira/Google Drive IDs, then run 'sat-cli onboard' to sync.");
    }
}
