import { input } from "@inquirer/prompts";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { getLogger } from "log4js";
import { Marked } from "marked";
import { dirname, resolve } from "path";
import { Service } from "typedi";
import { z } from "zod";
import { BedrockKnowledgeBaseService } from "../integrations/aws/services/bedrock-knowledge-base.service";
import { getKnowledgeBaseChatMessages } from "../prompts/knowledge-base-chat.prompt";
import { ConfigService, OnboardConfig } from "../services/config-service";
import { LlmService } from "../services/llm-service";
import { OnboardService } from "../services/onboarding/onboard.service";
import { TypedCommand, TypedInputs } from "./base";

const logger = getLogger("OnboardCommand");
const { markedTerminal } = require("marked-terminal");
const terminalMarkdown = new Marked(
    markedTerminal({
        width: process.stdout.columns || 100,
        reflowText: false,
    }),
);

const INPUTS = [
    {
        name: "configOrSheet",
        description:
            "Path to the onboarding config JSON file, or Google Sheet URL/ID (default: .sateng/onboarding.json)",
        schema: z.string().optional(),
        argument: true,
    },
    {
        name: "project-name",
        description:
            "Limit sync (and --upload-to-s3) to just the matching '<project-name>' section of your onboarding config (case-insensitive), and use it as the output folder name (e.g. onboarding/<project-name>/confluence/...). Non-project (global) config entries are skipped when this is set.",
        schema: z.string().optional(),
    },
    {
        name: "project",
        description:
            'Limit --chat or --knowledge-base retrieval to documents indexed for this project (for example, --project "Saturam")',
        schema: z.string().optional(),
    },
    {
        name: "upload-to-s3",
        description:
            "Upload the documents synced in this run to the configured S3 bucket (requires AWS S3 to be configured via 'sat-cli init' → Cloud)",
        schema: z.boolean().optional(),
    },
    {
        name: "list",
        description: "List locally synced onboarding documents, grouped by project name, instead of syncing",
        schema: z.boolean().optional(),
    },
    {
        name: "knowledge-base",
        description:
            "Interactively ask questions against the configured Bedrock Knowledge Base and print retrieved chunks (Retrieve only — no answer generation), instead of syncing. Requires Bedrock Knowledge Base to be configured via 'sat-cli init' → Cloud",
        schema: z.boolean().optional(),
    },
    {
        name: "chat",
        description:
            "Interactively ask questions and get an answer generated by your configured LLM, grounded in context retrieved from the Bedrock Knowledge Base (RAG), instead of syncing. Requires both an AI/LLM provider (sat-cli init → AI / LLM providers) and Bedrock Knowledge Base (sat-cli init → Cloud) to be configured",
        schema: z.boolean().optional(),
    },
    {
        name: "format",
        description:
            "Write a sample .sateng/onboarding.json config (with example Confluence, Jira, and Google Drive entries) to the current directory, instead of syncing",
        schema: z.boolean().optional(),
    },
] as const;

const ONBOARDING_CONFIG_TEMPLATE = {
    _comment: "This is a configuration template for project onboarding. Replace placeholders with actual values.",
    confluence: {
        baseUrl: "https://your-domain.atlassian.net",
    },
    jira: {
        baseUrl: "https://your-domain.atlassian.net",
    },
    projects: {
        ExampleProject: {
            confluence: {
                _comment: "'pages' accepts Confluence page IDs (as strings). 'space' syncs every page in that space key.",
                pages: ["123456789"],
                space: "PROJ",
            },
            jira: {
                _comment: "'tickets' accepts Jira issue keys. Use 'jql' instead to sync all issues matching a query.",
                tickets: ["PROJ-123"],
            },
            googleDocs: {
                _comment: "'docs' accepts Google Docs/Sheets/.docx file IDs from the file's Google Drive URL.",
                docs: ["your-google-doc-id-here"],
            },
            googleSheets: {
                _comment: "A single Google Sheet to sync as structured data. 'range' is optional (A1 notation).",
                spreadsheetId: "your-google-sheet-id-here",
                range: "Sheet1!A1:E100",
            },
            onboardingSheets: [
                {
                    _comment:
                        "A Google Sheet whose cells contain Confluence/Jira/Drive links to resolve and sync automatically.",
                    spreadsheetId: "your-onboarding-links-sheet-id-here",
                },
            ],
        },
    },
};

@Service()
export class OnboardCommand implements TypedCommand<typeof INPUTS> {
    readonly name = "onboard";
    readonly description =
        "Fetch and sync project onboarding documents locally (e.g. Confluence pages, Jira tickets, and Google Drive files)";
    readonly category = "common" as const;
    readonly aliases = ["ob", "onboarding"];
    readonly inputs = INPUTS;

    constructor(
        private readonly onboardService: OnboardService,
        private readonly configService: ConfigService,
        private readonly knowledgeBase: BedrockKnowledgeBaseService,
        private readonly llmService: LlmService,
    ) {}

    public async execute(inputs: Partial<TypedInputs<typeof INPUTS>>): Promise<void> {
        if (inputs.format) {
            this.writeSampleConfig();
            return;
        }

        if (inputs.chat) {
            await this.runChatSearch(inputs.project);
            return;
        }

        if (inputs["knowledge-base"]) {
            await this.runKnowledgeBaseSearch(inputs.project);
            return;
        }

        if (inputs.list) {
            await this.onboardService.listSyncedDocuments();
            return;
        }

        const cwd = process.env.SATENG_ORIGINAL_CWD ?? process.cwd();
        const arg = inputs.configOrSheet;
        const projectNameOverride = inputs["project-name"];
        const uploadToS3 = inputs["upload-to-s3"];

        const isGoogleSheet = arg && (arg.includes("docs.google.com/spreadsheets") || /^[a-zA-Z0-9-_]{44}$/.test(arg));

        if (isGoogleSheet) {
            const spreadsheetId = arg.includes("docs.google.com/spreadsheets")
                ? arg.match(/\/d\/([a-zA-Z0-9-_]+)/)?.[1] || arg
                : arg;

            logger.info(`Running onboarding sync directly from Google Sheet ID: ${spreadsheetId}`);
            await this.syncFromSheet(spreadsheetId, cwd, projectNameOverride, uploadToS3);
            return;
        }

        const configPath = arg ? resolve(arg) : resolve(cwd, ".sateng/onboarding.json");

        // A config file previously mirrored from a structured Google Sheet (see saveResolvedConfig)
        // carries a _sourceGoogleSheetId marker — re-check the sheet for the latest values on every
        // run instead of trusting the possibly-stale local mirror. Deleting the marker (or hand-editing
        // the file without it) detaches the file and it's treated as a plain local config again.
        const sourceSheetId = this.readSourceSheetId(configPath);
        if (sourceSheetId) {
            logger.info(
                `${configPath} was generated from Google Sheet ${sourceSheetId} — re-checking the sheet for the latest values...`,
            );
            await this.syncFromSheet(sourceSheetId, cwd, projectNameOverride, uploadToS3);
            return;
        }

        logger.info(`Loading onboarding configuration from: ${configPath}`);
        const parsedConfig = await this.configService.loadOnboardingConfig(configPath);
        const { filesWritten } = await this.onboardService.sync(parsedConfig, cwd, projectNameOverride);
        if (uploadToS3) await this.onboardService.uploadToS3(filesWritten);
    }

    /** Resolves a structured project config from the given sheet, mirrors it locally, and syncs it. */
    private async syncFromSheet(
        spreadsheetId: string,
        cwd: string,
        projectNameOverride: string | undefined,
        uploadToS3: boolean | undefined,
    ): Promise<void> {
        const parsedConfig = await this.onboardService.resolveConfigFromSheet(spreadsheetId);
        if (parsedConfig.projects && Object.keys(parsedConfig.projects).length > 0) {
            this.saveResolvedConfig(parsedConfig, cwd, spreadsheetId);
        }
        const { filesWritten } = await this.onboardService.sync(parsedConfig, cwd, projectNameOverride);
        if (uploadToS3) await this.onboardService.uploadToS3(filesWritten);
    }

    /** Reads the _sourceGoogleSheetId marker from a previously sheet-mirrored config file, if any. */
    private readSourceSheetId(configPath: string): string | undefined {
        if (!existsSync(configPath)) return undefined;
        try {
            const raw = JSON.parse(readFileSync(configPath, "utf-8"));
            return typeof raw?._sourceGoogleSheetId === "string" ? raw._sourceGoogleSheetId : undefined;
        } catch {
            return undefined;
        }
    }

    /**
     * When syncing directly from a structured project sheet, mirrors the resolved config to
     * .sateng/onboarding.json — refreshed on every run (including plain `sat-cli onboard` with
     * no argument, via the _sourceGoogleSheetId marker — see readSourceSheetId) so it always
     * reflects the sheet's latest state, and so the sheet-derived config can be
     * inspected/diffed locally like any other onboarding.json.
     */
    private saveResolvedConfig(config: OnboardConfig, cwd: string, sourceSheetId: string): void {
        const configDir = resolve(cwd, ".sateng");
        const targetPath = resolve(configDir, "onboarding.json");
        const withSource = {
            _comment:
                "Auto-generated from a structured onboarding Google Sheet. Running 'sat-cli onboard' " +
                "(with no argument) re-fetches the sheet and overwrites this file each time — edit the " +
                "sheet, not this file. To detach and edit this file directly instead, delete the " +
                "_sourceGoogleSheetId field below.",
            _sourceGoogleSheetId: sourceSheetId,
            ...config,
        };

        mkdirSync(configDir, { recursive: true });
        writeFileSync(targetPath, `${JSON.stringify(withSource, null, 4)}\n`, "utf-8");
        logger.info(`Saved resolved onboarding config from Google Sheet to: ${targetPath}`);
    }

    /**
     * Writes a sample .sateng/onboarding.json to the current directory so users can see
     * how to structure Confluence, Jira, and Google Drive (Docs/Sheets) entries. Never
     * overwrites an existing onboarding.json — writes alongside it as onboarding.sample.json
     * instead.
     */
    private writeSampleConfig(): void {
        const cwd = process.env.SATENG_ORIGINAL_CWD ?? process.cwd();
        const configDir = resolve(cwd, ".sateng");
        const targetPath = resolve(configDir, "onboarding.json");
        const outputPath = existsSync(targetPath) ? resolve(configDir, "onboarding.sample.json") : targetPath;

        mkdirSync(configDir, { recursive: true });
        writeFileSync(outputPath, `${JSON.stringify(ONBOARDING_CONFIG_TEMPLATE, null, 4)}\n`, "utf-8");

        if (outputPath !== targetPath) {
            logger.info(`.sateng/onboarding.json already exists — wrote sample config to: ${outputPath}`);
        } else {
            logger.info(`Sample onboarding config written to: ${outputPath}`);
        }
        logger.info("Edit it with your Confluence/Jira/Google Drive IDs, then run 'sat-cli onboard' to sync.");
    }

    private static readonly KB_EXIT_COMMANDS = new Set(["exit", "quit", ":q"]);
    private static readonly LOADING_FRAMES = ["-", "\\", "|", "/"];

    private normalizeProjectName(projectName?: string): string | undefined {
        if (!projectName?.trim()) return undefined;
        return (
            projectName
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, "-")
                .replace(/(^-|-$)/g, "") || undefined
        );
    }

    /**
     * Prompts for one question. Returns the trimmed question, or null to signal the REPL
     * should exit — on blank input, "exit"/"quit"/":q", or Ctrl+C (inquirer's ExitPromptError).
     */
    private async promptQuestion(): Promise<string | null> {
        let question: string;
        try {
            question = await input({
                message: "Ask Saturam-CLI :",
                theme: { prefix: { idle: "🤖", done: "🤖" } },
            });
        } catch (err) {
            if (err instanceof Error && err.name === "ExitPromptError") {
                return null;
            }
            throw err;
        }
        const trimmed = question.trim();
        if (!trimmed || OnboardCommand.KB_EXIT_COMMANDS.has(trimmed.toLowerCase())) {
            return null;
        }
        return trimmed;
    }

    private async withLoading<T>(message: string, task: () => Promise<T>): Promise<T> {
        if (!process.stderr.isTTY) {
            return task();
        }

        let frameIndex = 0;
        const render = () => {
            const frame = OnboardCommand.LOADING_FRAMES[frameIndex % OnboardCommand.LOADING_FRAMES.length];
            process.stderr.write(`\r${frame} ${message}...`);
            frameIndex += 1;
        };

        render();
        const timer = setInterval(render, 120);
        try {
            return await task();
        } finally {
            clearInterval(timer);
            process.stderr.write(`\r${" ".repeat(message.length + 6)}\r`);
        }
    }

    /**
     * Interactive REPL: repeatedly prompts for a question, calls Bedrock Knowledge Base
     * Retrieve (no generation — equivalent to the AWS console's "Retrieve only" test mode),
     * and prints the ranked chunks. Exits on blank input, "exit"/"quit", or Ctrl+C.
     */
    private async runKnowledgeBaseSearch(projectName?: string): Promise<void> {
        const project = this.normalizeProjectName(projectName);
        logger.info("Bedrock Knowledge Base search (Retrieve only — no answer generation).");
        if (project) logger.info(`Project filter: ${project}`);
        logger.info("Type a question and press Enter. Type 'exit' or leave blank to quit.\n");

        for (;;) {
            const question = await this.promptQuestion();
            if (question === null) {
                logger.info("Exiting knowledge base search.");
                return;
            }

            try {
                const results = await this.withLoading("Retrieving matching knowledge base chunks", () =>
                    project
                        ? this.knowledgeBase.retrieve(question, { project })
                        : this.knowledgeBase.retrieve(question),
                );
                if (results.length === 0) {
                    logger.info("No matching results found.\n");
                    continue;
                }

                logger.info(`\nFound ${results.length} result(s):`);
                results.forEach((result, index) => {
                    const scoreText = result.score !== undefined ? ` (score: ${result.score.toFixed(3)})` : "";
                    logger.info(`\n${index + 1}.${scoreText}`);
                    if (result.location) logger.info(`   source: ${result.location}`);
                    if (result.metadata && Object.keys(result.metadata).length > 0) {
                        logger.info(`   metadata: ${JSON.stringify(result.metadata)}`);
                    }
                    logger.info(`   ${result.content.trim()}`);
                });
                logger.info("");
            } catch (err) {
                logger.error(`Retrieval failed: ${(err as Error).message}\n`);
            }
        }
    }

    private stripInlineCitations(answer: string): string {
        return answer.replace(/\s*\[(?:\d+(?:\s*,\s*\d+)*)\]/g, "");
    }

    private renderAnswer(answer: string): string {
        const cleaned = this.stripInlineCitations(answer).trim();
        if (!process.stdout.isTTY) {
            return cleaned;
        }
        return String(terminalMarkdown.parse(cleaned)).trimEnd();
    }

    private printSources(chunks: Array<{ location?: string }>): void {
        const sources = Array.from(new Set(chunks.map((chunk) => chunk.location).filter(Boolean)));
        if (sources.length === 0) return;

        logger.info("Sources:");
        sources.forEach((source) => logger.info(`- ${source}`));
        logger.info("");
    }

    /**
     * Interactive RAG chat REPL: for each question, retrieves context from the Bedrock
     * Knowledge Base and sends it plus the question to the configured LLM, printing the
     * generated answer with sources. Requires an LLM provider to be configured
     * first — checked once up front with a clear suggestion if none is found.
     */
    private async runChatSearch(projectName?: string): Promise<void> {
        const hasLlm = await this.configService.hasAnyLLMProviderConfigured();
        if (!hasLlm) {
            logger.warn("No AI/LLM provider is configured yet.");
            logger.info(
                "Run 'sat-cli init' and select 'AI / LLM providers' to configure one (Anthropic, OpenAI, Gemini, Bedrock, etc.), then try 'sat-cli onboard --chat' again.",
            );
            return;
        }

        const project = this.normalizeProjectName(projectName);
        logger.info("Knowledge Base chat (RAG) — ask a question; it's answered by your configured LLM,");
        logger.info("grounded in context retrieved from the Bedrock Knowledge Base.");
        if (project) logger.info(`Project filter: ${project}`);
        logger.info("Type a question and press Enter. Type 'exit' or leave blank to quit.\n");

        for (;;) {
            const question = await this.promptQuestion();
            if (question === null) {
                logger.info("Exiting knowledge base chat.");
                return;
            }

            try {
                const { chunks, answer } = await this.withLoading(
                    "Retrieving context and generating answer",
                    async () => {
                        const chunks = project
                            ? await this.knowledgeBase.retrieve(question, { project })
                            : await this.knowledgeBase.retrieve(question);
                        const { system, user } = getKnowledgeBaseChatMessages({ question, chunks, project });
                        const answer = await this.llmService.prompt([system, user]);
                        return { chunks, answer };
                    },
                );

                logger.info(`\n${this.renderAnswer(answer)}\n`);
                this.printSources(chunks);
            } catch (err) {
                logger.error(`Chat failed: ${(err as Error).message}\n`);
            }
        }
    }
}
